version: '3.8'

networks:
  default:

services:

  MuseumAPI:
    image: openjdk:latest
    working_dir: /app
    volumes:
      - ./MuseumAPI:/app
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run

  museum-api:
    build:
      context: ./museum-api
    volumes:
      - ./museum-api:/app
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0.36
    container_name: museum_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: some_pass
      MYSQL_DATABASE: museum_db
      MYSQL_USER: springuser2
      MYSQL_PASSWORD: springuser2