version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: some_pass
      MYSQL_DATABASE: museum_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springuser

  backend:
    image: maven:3.8.5-openjdk-17
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/target
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/museum_db
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springuser  
    command: mvn spring-boot:run

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - "/app/node_modules"
    ports:
      - "3000:3000"

  