version: '3.8'

networks:
  default:

services:

  backend:
    image: openjdk:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0.36
    container_name: museum_project_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: some_pass
      MYSQL_DATABASE: museum_db
      MYSQL_USER: springuser2
      MYSQL_PASSWORD: springuser2